export const CATEGORIES = [
  { value: 'technology', label: 'TECHNOLOGY' },
  { value: 'design', label: 'DESIGN' },
  { value: 'business', label: 'BUSINESS' },
  { value: 'health', label: 'HEALTH' },
  { value: 'education', label: 'EDUCATION' },
  { value: 'art', label: 'ART' },
  { value: 'science', label: 'SCIENCE' },
  { value: 'sports', label: 'SPORT' },
  { value: 'travel', label: 'TRAVELING' },
  { value: 'food', label: 'FOOD' },
  { value: 'ai', label: 'AI' },
  { value: 'innovation', label: 'INNOVATION' },
  { value: 'culture', label: 'CULTURE' },
  { value: 'mindfulness', label: 'MINDFULNESS' },
  { value: 'relationships', label: 'RELATIONSHIPS' },
  { value: 'psychology', label: 'PSYCHOLOGY' },
  { value: 'finance', label: 'FINANCE' },
  { value: 'architecture', label: 'ARCHITECTURE' },
  { value: 'construction', label: 'CONSTRUCTION' },
];
